#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${CARLITO_INSTALL_E2E_IMAGE:-carlito-install-e2e:local}"
INSTALL_URL="${CARLITO_INSTALL_URL:-https://carlito.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
CARLITO_E2E_MODELS="${CARLITO_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker"

echo "==> Run E2E installer test"
docker run --rm \
  -e CARLITO_INSTALL_URL="$INSTALL_URL" \
  -e CARLITO_INSTALL_TAG="${CARLITO_INSTALL_TAG:-latest}" \
  -e CARLITO_E2E_MODELS="$CARLITO_E2E_MODELS" \
  -e CARLITO_INSTALL_E2E_PREVIOUS="${CARLITO_INSTALL_E2E_PREVIOUS:-}" \
  -e CARLITO_INSTALL_E2E_SKIP_PREVIOUS="${CARLITO_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e CARLITO_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS="${CARLITO_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS:-600}" \
  -e CARLITO_NO_ONBOARD=1 \
  -e OPENAI_API_KEY \
  -e ANTHROPIC_API_KEY \
  -e ANTHROPIC_API_TOKEN \
  "$IMAGE_NAME"
