export const browserCoreExamples = [
  "carlito browser status",
  "carlito browser start",
  "carlito browser stop",
  "carlito browser tabs",
  "carlito browser open https://example.com",
  "carlito browser focus abcd1234",
  "carlito browser close abcd1234",
  "carlito browser screenshot",
  "carlito browser screenshot --full-page",
  "carlito browser screenshot --ref 12",
  "carlito browser snapshot",
  "carlito browser snapshot --format aria --limit 200",
  "carlito browser snapshot --efficient",
  "carlito browser snapshot --labels",
];

export const browserActionExamples = [
  "carlito browser navigate https://example.com",
  "carlito browser resize 1280 720",
  "carlito browser click 12 --double",
  'carlito browser type 23 "hello" --submit',
  "carlito browser press Enter",
  "carlito browser hover 44",
  "carlito browser drag 10 11",
  "carlito browser select 9 OptionA OptionB",
  "carlito browser upload /tmp/carlito/uploads/file.pdf",
  'carlito browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "carlito browser dialog --accept",
  'carlito browser wait --text "Done"',
  "carlito browser evaluate --fn '(el) => el.textContent' --ref 7",
  "carlito browser console --level error",
  "carlito browser pdf",
];
